### ISSUE TITLE
Leaderboards

### ISSUE THREAD

**Issue by DorinR** [DorinR/COMP472-Project1-D1#37]
As a user, I would like to be able to compare the number of steps it took me to solve a given puzzle compared to other people in the world.

- [ ] Add a counter to the current puzzle
- [ ] When puzzle is complete, save to the user's account that number (for a given size-difficulty combo)
- [ ] Have a Leaderboards page that displays the rankings showing usernames and moves made (for a given size-difficulty combo)
- [ ] Infinitely scrolling table is a bit non-scalable, probably show like top 50 then if you're outside that 50, display an extra row with ur ranking and username.
Consider having the leaderboards on the same page as the puzzle?
